/**
 * Persisted store for community posts created by the user (via the + FAB on
 * the community feed or "Post to Community" from the Meal Mate recipe card).
 *
 * The backend has a `/api/v1/community/posts` endpoint, but the current
 * community feed on the home tab reads from the static RECIPES bundle — so we
 * mirror posts into AsyncStorage and prepend them to that feed. This gives the
 * user a visible "my post" in the demo even when they're not signed in.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import { Image as ExpoImage } from 'expo-image';

import type { ChatRecipePayload } from '@/services/api';
import { getCurrentUserId, getCurrentUserName } from '@/services/current-user-store';
import { aiGeneratedFoodImage, isStaleAiImage } from '@/utils/synthesize-recipe-facts';

export interface UserPost {
  id: string;
  title: string;
  description: string;
  ingredients: string;
  imageUri: string | null;
  /** Primary / first selected category. Kept for backwards-compat rendering. */
  tag: string | null;
  /** Full list of selected categories (may be multiple). `tag` mirrors `tags[0]`. */
  tags?: string[];
  created_at: string;
  /**
   * Whether this post was originally generated by Meal Mate. Used to promote
   * it into the "Saved AI Recipes" strip in the Bookmarks tab when the user
   * bookmarks a community card that was AI-authored.
   */
  ai_origin?: boolean;
  /** Snapshot of the AI recipe payload (macros, why-this-works, etc). */
  ai_recipe?: ChatRecipePayload | null;
  /**
   * Supabase user id of the account that created this post. Used to gate
   * "Yours" badges and delete buttons so other signed-in accounts see the
   * post in the community feed but can't mutate it. `null` = legacy post
   * saved before this field existed.
   */
  author_user_id?: string | null;
  /**
   * Display name of the author at the time the post was created (snapshot
   * — never updated even if the author renames themselves later). Surfaced
   * as a "by …" byline on community cards so other accounts can see who
   * posted each recipe. `null` = legacy post or anonymous demo session.
   */
  author_name?: string | null;
}

const STORAGE_KEY = 'nutriculture.userPosts.v1';

let posts: UserPost[] = [];
let hydrated = false;
let hydrationPromise: Promise<void> | null = null;
const listeners = new Set<() => void>();

function notify() {
  listeners.forEach((l) => l());
}

async function persist(): Promise<void> {
  try {
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(posts));
  } catch {
    // ignore — non-fatal
  }
}

export function hydrateUserPosts(): Promise<void> {
  if (hydrated) return Promise.resolve();
  if (hydrationPromise) return hydrationPromise;
  hydrationPromise = (async () => {
    try {
      const raw = await AsyncStorage.getItem(STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) {
          posts = parsed.filter((p) => p && typeof p.id === 'string');
        }
      }
    } catch {
      posts = [];
    }
    // Backfill / migrate images:
    //   - Missing imageUri → fill with AI-generated food photo
    //   - Previously-stored Unsplash stock photos → migrate to AI-generated
    //     (they were inaccurate to the actual recipe)
    //   - User-uploaded photos (file://, custom hosts) → leave untouched
    let didBackfill = false;
    posts = posts.map((p) => {
      if (p.imageUri && !isStaleAiImage(p.imageUri)) return p;
      const seed = Math.abs(
        Array.from(p.id).reduce((h, c) => ((h << 5) - h + c.charCodeAt(0)) | 0, 0),
      ) || 1;
      didBackfill = true;
      return {
        ...p,
        imageUri: aiGeneratedFoodImage(
          p.title || 'home cooked meal',
          seed,
          p.ingredients,
        ),
      };
    });
    if (didBackfill) await persist();
    // Warm the image cache for every post so the feed cards render instantly
    // the first time the user opens the community tab.
    const urls = posts.map((p) => p.imageUri).filter((u): u is string => !!u);
    if (urls.length > 0) void ExpoImage.prefetch(urls, 'memory-disk');
    hydrated = true;
    notify();
  })();
  return hydrationPromise;
}

export function getUserPosts(): UserPost[] {
  return posts;
}

export async function addUserPost(
  input: Omit<UserPost, 'id' | 'created_at'>,
): Promise<UserPost> {
  const id = `user-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  // Mirror the AI-recipe behaviour: if the user didn't pick their own photo,
  // generate a stable pollinations fallback from the recipe title so all
  // feed cards render with an image.
  let resolvedImageUri = input.imageUri;
  if (!resolvedImageUri) {
    const seed = Math.abs(
      Array.from(id).reduce((h, c) => ((h << 5) - h + c.charCodeAt(0)) | 0, 0),
    ) || 1;
    // Use the user's free-text ingredients as a hint so the generated image
    // actually resembles their dish (e.g. "Thai basil chicken stir fry" →
    // Thai basil chicken photo, not a random bowl).
    resolvedImageUri = aiGeneratedFoodImage(
      input.title || 'home cooked meal',
      seed,
      input.ingredients,
    );
  }
  const entry: UserPost = {
    ...input,
    imageUri: resolvedImageUri,
    id,
    created_at: new Date().toISOString(),
    // Stamp with the currently-signed-in user so only they see the
    // "Yours" badge / delete button on this post, and snapshot their
    // display name so other accounts can see who authored it.
    author_user_id: input.author_user_id ?? getCurrentUserId(),
    author_name: input.author_name ?? getCurrentUserName(),
  };
  posts = [entry, ...posts];
  // Start prefetching the image immediately so the feed card shows a decoded
  // image the moment the user navigates back to the community tab.
  if (resolvedImageUri) void ExpoImage.prefetch(resolvedImageUri, 'memory-disk');
  await persist();
  notify();
  return entry;
}

export async function removeUserPost(id: string): Promise<void> {
  // Only let the current signed-in user delete posts they authored. Posts
  // without an `author_user_id` are pre-scoping legacy posts — we allow
  // those to be removed by anyone so users can clean them up. Callers
  // that come from UI paths already gate the delete button on ownership,
  // but this is a server-side-style check in case that UI is bypassed.
  const target = posts.find((p) => p.id === id);
  if (!target) return;
  const currentUid = getCurrentUserId();
  if (target.author_user_id && target.author_user_id !== currentUid) {
    return;
  }
  posts = posts.filter((p) => p.id !== id);
  await persist();
  notify();
}

export function subscribeUserPosts(listener: () => void): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}
